package com.youtube;


import java.util.Arrays;
import java.util.List;



























import utils.Blockgenerator;
import utils.GuiHandler;
import utils.KohlewerkCreativeTab;





import com.youtube.blocks.BlockMaschC;
import com.youtube.blocks.BlockOreMaschC;
import com.youtube.blocks.Tilenentitys.TileEntityMaschC;
import com.youtube.items.ItemKoks;

import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid = KohleWerk.MODID)
public class KohleWerk {
    
	//Variablen
	public static final String MODID = "kohlewerk";
    
	public static Item koks = new ItemKoks();
 
	
	public static Block maschcore = new BlockOreMaschC();
	
	
	
	
	public static final int GUIMASCHC = 0;

	
	List<String> authors = Arrays.asList("Jan");
	
	public static Block blockmaschc = new BlockMaschC();
	
	
	@Instance
	public static KohleWerk instance;
	
  
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event){
		
		
		GameRegistry.addSmelting(new ItemStack(this.koks, 15), new ItemStack(Items.diamond), 10000);

		
		
		
		
		//GuiHandler

		NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());
		
		//TileEntitys
		
		GameRegistry.registerTileEntity(TileEntityMaschC.class, "TileEntityMaschC");

	
		
		
		ModMetadata ModData =  event.getModMetadata();
		modinfo(ModData);
		
		
		
	}
	
	@EventHandler
	public void Init(FMLInitializationEvent event){
		GameRegistry.registerBlock(blockmaschc, "maschc");
		Item itemfromblock = Item.getItemFromBlock(blockmaschc);
		
		GameRegistry.registerItem(koks, "koks");
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(koks, 0, new ModelResourceLocation("kohlewerk:koks", "inventory"));
		
		
		
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemfromblock, 0, new ModelResourceLocation("kohlewerk:maschc", "inventory"));
        
		GameRegistry.registerBlock(maschcore, "maschcore");
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(maschcore), 0, new ModelResourceLocation("kohlewerk:maschcore", "inventory"));
				
		
		
		
		GameRegistry.registerWorldGenerator(new Blockgenerator(blockmaschc), 0);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event){
		
	}
   
	public void modinfo(ModMetadata data){
		//Modinfos setzten
		
		data.autogenerated = false;
		data.name = EnumChatFormatting.BLUE +  "" + EnumChatFormatting.BOLD  + "Kohle Werk";
		data.authorList = authors;
		data.description = "Dieser Mod fügt ein Brennstofftransformierer hinzu";
		data.credits = "HyCraftHD";
		data.logoFile = "assets/kohlewerk/textures/logo/logo.png";
		data.version= "0.1";
	}
	
	
	
}
